### ISSUE TITLE
People need invites to join the slack channel

### ISSUE THREAD

**Issue by NotMyself** [SouthSoundDevelopers/CVPZ#20]
Currently if people want to get into the SSDUG slack, someone has to send them an invite. This makes it prohibitively difficult for new people to join what is effectively a open chat.

[Shayne Boyer](http://tattoocoder.com/asp-net-core-slack-community/) setup a [site](http://tattoocoder.com/aspnet-slack-sign-up/) that automatically sends invites out for the [.NET Core Slack](https://aspnetcore.slack.com/). It appears to use this [codebase](https://github.com/rauchg/slackin).

Let's look into setting this up for SSDUG

**Comment by emragins** [comment]
Looks like this is powered by https://github.com/rauchg/slackin

**Comment by NotMyself** [comment]
Yeah sorry that's what the codebase link points at. Sorry if I wasn't clear.

**Comment by emragins** [comment]
Only a month later. ;)

https://ssdug-slackin.azurewebsites.net/

**Comment by CarBar** [comment]
Did you validate with an email address? It would be awesome to close this!

**Comment by emragins** [comment]
Yep.‎ You should probably add it to the readme, and let people know to join #cvpz.

**Comment by NotMyself** [comment]
So is this issue closed now?

**Comment by CarBar** [comment]
If Eve validated it, then yes. Yay!
