### ISSUE TITLE
AppVeyor Builds Run Under McLeopold's Account

### ISSUE THREAD

**Issue by NotMyself** [SouthSoundDevelopers/CVPZ#29]
Currently our AppVeyor build is setup through @McLeopold's account. We should remove @McLeopold's account from the build chain. To do this we need a service account for GitHub. 

Here are the steps I think are needed:

- [x] Create new email account for service account.
- [x] Create GitHub account using service account email.
- [x] Add GitHub account to SSD organization.
- [x] Signing into AppVeyor using GitHub service account.
- [x] Create new build using the service account.
- [x] Update encrypted slack token in the appveyor.yml.
- [x] Update readme.md badge to point to new build's master branch.

**Comment by emragins** [comment]
I created SouthSoundDevelopers@gmail.com yesterday for the slack-inviter.  There is also ssdug-admin@googlegroups.com, but for some reason either slack or google refused the slack invite message, so I couldn't convert it to a user in slack (bot tokens didn't have permissions to invite users).

Unless you want to go with a specific CVPZ service account, we can use SouthSoundDevelopers@gmail.com.

Let me know if you want to go forward with this, and I'd be happy to share the password with a select few.

**Comment by NotMyself** [comment]
Ok this work is completed. Eve and I worked on it this evening.
