### ISSUE TITLE
Create CVPZ.UI project

### ISSUE THREAD

**Issue by bivvo** [SouthSoundDevelopers/CVPZ#4]
If we are going to separate the UI as @CarBar mentioned. We will want to create new repo to house those files. This task should be for creating the repo, and creating the skeleton of the project.

**Comment by CarBar** [comment]
Agreed. Should we then look at the entire structure? CVPZ.UI and CVPZ.API?

**Comment by CarBar** [comment]
Also should we call that the CVPZ.WebUI as I would like a view able end result to have a mobile front end?

**Comment by bivvo** [comment]
Yes, If there are going to be multiple front ends. The WebUI should be responsive. Should this application be designed mobile first, or desktop first?

**Comment by CarBar** [comment]
My thoughts are that the web will be full featured and the mobile will only have a search and display functionality. Certainly we could make it responsive, but I would think limited functionality on the client would be so much different than the full web version that it would be to our advantage to have a separate solution. Just my thought. We have also talked about having a version constructed in electron. More to play with electron than anything...  Thoughts?

**Comment by bivvo** [comment]
Lets just go with the full webui for now. I would say worry about the other UI options at a later date.

**Comment by bivvo** [comment]
@CarBar done. Closing out. Put all further issues in the UI project.
