### ISSUE TITLE
Decide on one place to manage project

### ISSUE THREAD

**Issue by CarBar** [SouthSoundDevelopers/CVPZ#7]
@McLeopold @bivvo @TumboTheGnome 
Should we have one place to manage tasks for all repos as we have a few now and there is not a single place for milestones, issues, etc...?

Trello? Any other free and awesome things out there?

**Comment by TumboTheGnome** [comment]
Trello looks like a good option. If we go with it I'd like to see a link included on the CVPZ readme.

**Comment by emragins** [comment]
It looks like you did find the Project / task board. What does trello give you that the task board doesn't?  Bear in mind I like trello, but I like having everything in one place even more.  This is especially true when you (I) start thinking discoverability, user management and synchronization.

**Comment by CarBar** [comment]
So we are playing with Project and Notes, then converting them into issues. It appears that we can manage them on the Organizations board, and set the repo when we convert things into issues.

My tendency when I see what is there is to build a scrum board of sorts, but I think we may benefit from different swim lanes on the Organization Project and then maybe scrum style boards per repo. Thoughts?
